#!/bin/bash
# ============================================
#  CT LLC Scraper - One-Click Installer
#  Hammer & Pixels Lead Generation
# ============================================
set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${BOLD}======================================"
echo "  CT LLC Scraper - Installer"
echo "  Hammer & Pixels Lead Generation"
echo -e "======================================${NC}"
echo ""

# --- Check for Docker ---
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker not found. Installing...${NC}"
    if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose-plugin
        sudo systemctl enable --now docker
        sudo usermod -aG docker "$USER"
        echo -e "${YELLOW}You were added to the docker group. If the build fails, log out and back in, then re-run this script.${NC}"
    elif command -v dnf &> /dev/null; then
        sudo dnf install -y docker docker-compose-plugin
        sudo systemctl enable --now docker
        sudo usermod -aG docker "$USER"
        echo -e "${YELLOW}You were added to the docker group. If the build fails, log out and back in, then re-run this script.${NC}"
    else
        echo -e "${RED}Cannot auto-install Docker on this system.${NC}"
        echo "Install Docker manually: https://docs.docker.com/engine/install/"
        exit 1
    fi
fi

# Check docker compose availability
if docker compose version &> /dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose &> /dev/null 2>&1; then
    COMPOSE="docker-compose"
else
    echo -e "${RED}Docker Compose not found.${NC}"
    echo "Install it: sudo apt-get install docker-compose-plugin"
    exit 1
fi

echo -e "${GREEN}Docker found.${NC}"
echo ""

# --- Check for Proton Mail Bridge ---
echo -e "${BOLD}Proton Mail Bridge Setup${NC}"
echo "This app sends emails through Proton Mail Bridge running on this machine."
echo ""

BRIDGE_RUNNING=false
if ss -tlnp 2>/dev/null | grep -q ':1025 ' || netstat -tlnp 2>/dev/null | grep -q ':1025 '; then
    echo -e "${GREEN}Proton Mail Bridge detected on port 1025.${NC}"
    BRIDGE_RUNNING=true
else
    echo -e "${YELLOW}Proton Mail Bridge not detected on port 1025.${NC}"
    echo "Make sure Bridge is installed and running before sending emails."
    echo "The app will still start -- you can configure SMTP from the dashboard."
fi
echo ""

# --- Configure .env ---
ENV_FILE="$(dirname "$0")/.env"

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Existing .env found.${NC}"
    read -rp "Overwrite configuration? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        echo ""
    else
        rm "$ENV_FILE"
    fi
fi

if [ ! -f "$ENV_FILE" ]; then
    echo -e "${BOLD}Configuration${NC}"
    echo ""

    # Proton email
    read -rp "Proton Mail email address: " SMTP_EMAIL
    echo ""

    # Bridge password
    echo "Enter your Proton Mail Bridge password."
    echo "(Find it in Bridge > Settings > your account > SMTP credentials)"
    read -rsp "Bridge SMTP password: " SMTP_PASSWORD
    echo ""
    echo ""

    # SMTP port (Bridge default is 1025, but some setups use 25 or others)
    read -rp "Bridge SMTP port [1025]: " SMTP_PORT
    SMTP_PORT=${SMTP_PORT:-1025}

    # Security: Bridge supports STARTTLS by default
    read -rp "SMTP security (starttls/ssl) [starttls]: " SMTP_SECURITY
    SMTP_SECURITY=${SMTP_SECURITY:-starttls}

    # From name
    read -rp "From name for outreach emails [Jesse]: " FROM_NAME
    FROM_NAME=${FROM_NAME:-Jesse}

    # Site URL
    read -rp "Your website URL [https://hammerandpixels.com]: " SITE_URL
    SITE_URL=${SITE_URL:-https://hammerandpixels.com}

    # API key for remote access (optional)
    API_KEY=$(openssl rand -hex 24 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(24))")
    echo ""
    echo -e "Generated API key for remote access: ${BOLD}${API_KEY}${NC}"
    echo "(Only needed if accessing the dashboard from another machine)"

    cat > "$ENV_FILE" <<ENVEOF
# CT LLC Scraper Configuration
# Generated by install.sh on $(date)

# Proton Mail Bridge SMTP
SMTP_EMAIL=${SMTP_EMAIL}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_SERVER=127.0.0.1
SMTP_PORT=${SMTP_PORT}
SMTP_SECURITY=${SMTP_SECURITY}

# Email settings
EMAIL_FROM_NAME=${FROM_NAME}
SITE_URL=${SITE_URL}

# API key for remote dashboard access (localhost is always allowed)
LLCSCRAPER_API_KEY=${API_KEY}

# Flask
FLASK_DEBUG=false
ENVEOF

    chmod 600 "$ENV_FILE"
    echo ""
    echo -e "${GREEN}.env created and locked down (chmod 600).${NC}"
fi

echo ""

# --- Build and start ---
echo -e "${BOLD}Building and starting LLC Scraper...${NC}"
echo ""

cd "$(dirname "$0")"
$COMPOSE up --build -d

echo ""
echo -e "${BOLD}${GREEN}======================================"
echo "  LLC Scraper is running!"
echo "======================================${NC}"
echo ""
echo -e "  Dashboard:  ${BOLD}http://localhost:5075${NC}"
echo -e "  Logs:       ${BOLD}$COMPOSE logs -f${NC}"
echo -e "  Stop:       ${BOLD}$COMPOSE down${NC}"
echo -e "  Restart:    ${BOLD}$COMPOSE restart${NC}"
echo ""
if [ "$BRIDGE_RUNNING" = true ]; then
    echo -e "  ${GREEN}Proton Mail Bridge: connected${NC}"
else
    echo -e "  ${YELLOW}Proton Mail Bridge: not detected -- start Bridge before sending emails${NC}"
fi
echo ""
echo "  Open the dashboard to configure scrape schedule, review leads,"
echo "  and approve outreach emails."
echo ""
